# Generated by Django 6.0.5 on 2026-05-21 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componenti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acquisti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.IntegerField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='componenti.components')),
            ],
            options={
                'db_table': 'acquisti',
                'ordering': ['-data'],
            },
        ),
    ]
